"""auto update

Revision ID: 1af5660b86f4
Revises: 806c4c3baf77
Create Date: 2026-04-03 02:51:26.919417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1af5660b86f4'
down_revision: Union[str, Sequence[str], None] = '806c4c3baf77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badges', 'requirement')
    op.add_column('campaigns', sa.Column('impact_statement', sa.String(), nullable=True))
    op.alter_column('campaigns', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('campaigns', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('campaigns', 'raised_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default='0',
               existing_nullable=True)
    op.alter_column('campaigns', 'donor_count',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)
    op.alter_column('campaigns', 'share_count',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)
    op.alter_column('campaigns', 'click_count',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)
    op.alter_column('campaigns', 'status',
               existing_type=sa.VARCHAR(),
               server_default='active',
               existing_nullable=True)
    op.alter_column('campaigns', 'urgency_level',
               existing_type=sa.VARCHAR(),
               server_default='medium',
               existing_nullable=True)
    op.alter_column('campaigns', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=True)
    op.drop_column('campaigns', 'updated_at')
    op.alter_column('donations', 'payment_status',
               existing_type=sa.VARCHAR(),
               server_default='pending',
               existing_nullable=True)
    op.drop_column('donations', 'stripe_session_id')
    op.alter_column('referrals', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('referrals', 'clicks',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)
    op.alter_column('referrals', 'signups',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)
    op.alter_column('referrals', 'donations_count',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)
    op.alter_column('referrals', 'donations_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default='0',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referrals', 'donations_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('referrals', 'donations_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('referrals', 'signups',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('referrals', 'clicks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('referrals', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('donations', sa.Column('stripe_session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('donations', 'payment_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.add_column('campaigns', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('campaigns', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campaigns', 'urgency_level',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campaigns', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campaigns', 'click_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campaigns', 'share_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campaigns', 'donor_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campaigns', 'raised_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campaigns', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('campaigns', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('campaigns', 'impact_statement')
    op.add_column('badges', sa.Column('requirement', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###